#------------------------------------------------------------------#
# Please make sure to check the paths for data_root and result_root before running #
#------------------------------------------------------------------#

# Configure feature path
# **** Please set your own feature path manually before first running ****
data_root: &d_r your/feature/path/here
modelnet40_ft: !join [*d_r, your_modelnet40_feature_file.mat]
ntu2012_ft: !join [*d_r, your_ntu2012_feature_file.mat]

# Hypergraph configuration
graph_type: &g_t hypergraph
K_neigs: [10]
#K_neigs: [10, 15 ]
m_prob: 1.0
is_probH: True

#---------------------------------------
# Configure feature usage for structure construction
use_mvcnn_feature_for_structure: True
use_gvcnn_feature_for_structure: True
#---------------------------------------

# Model configuration
#--------------------------------------------------
# Select the dataset name you are using (name only for configuration logic, no dataset loading)
on_dataset: &o_d ModelNet40
#on_dataset: &o_d NTU2012
#--------------------------------------------------

#---------------------------------------
# Select the features to use as input
use_mvcnn_feature: False
use_gvcnn_feature: True
#---------------------------------------

# Result saving configuration
# **** Please set your result output path before running ****
result_root: &r_r your/result/output/path
result_sub_folder: !join [*r_r, !concat [ *g_t, _, *o_d ]]
ckpt_folder: !join [*r_r, ckpt]

# Training settings ( improvement configuration)
max_epoch: 200
n_hid: 30
lr: 0.00004
milestones: [100]
gamma: 0.9
drop_out: 0.5
print_freq: 50
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7
